CREATE TABLE IF NOT EXISTS tb_pessoa
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(200)                            NOT NULL,
    ativo       BOOLEAN                                 NOT NULL,
    logradouro  VARCHAR(200),
    numero      VARCHAR(10),
    complemento VARCHAR(100),
    bairro      VARCHAR(100),
    cep         VARCHAR(8),
    cidade      VARCHAR(100),
    estado      VARCHAR(100),
    CONSTRAINT pk_tb_pessoa PRIMARY KEY (id)
);

INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('João Silva', 'Rua do Abacaxi', '10', null, 'Brasil', '38400012', 'Uberlândia', 'MG', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Maria Rita', 'Rua do Sabiá', '110', 'Apto 101', 'Colina', '11400012', 'Ribeirão Preto', 'SP', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Pedro Santos', 'Rua da Bateria', '23', null, 'Morumbi', '54212012', 'Goiânia', 'GO', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Ricardo Pereira', 'Rua do Motorista', '123', 'Apto 302', 'Aparecida', '38400012', 'Salvador', 'BA', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Josué Mariano', 'Av Rio Branco', '321', null, 'Jardins', '56400012', 'Natal', 'RN', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Pedro Barbosa', 'Av Brasil', '100', null, 'Tubalina', '77400012', 'Porto Alegre', 'RS', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Henrique Medeiros', 'Rua do Sapo', '1120', 'Apto 201', 'Centro', '12400012', 'Rio de Janeiro', 'RJ', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Carlos Santana', 'Rua da Manga', '433', null, 'Centro', '31400012', 'Belo Horizonte', 'MG', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Leonardo Oliveira', 'Rua do Músico', '566', null, 'Segismundo Pereira', '38400000', 'Uberlândia', 'MG', true);
INSERT INTO tb_pessoa (nome, logradouro, numero, complemento, bairro, cep, cidade, estado, ativo) values ('Isabela Martins', 'Rua da Terra', '1233', 'Apto 10', 'Vigilato', '99400012', 'Manaus', 'AM', true);
