CREATE TABLE if not exists tb_categoria
(
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_tb_categoria PRIMARY KEY (id_categoria)
);

